# Generated by Django 6.0.3 on 2026-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_fr', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('order', models.PositiveIntegerField(default=0)),
                ('degree_fr', models.CharField(blank=True, default='', max_length=255)),
                ('degree_en', models.CharField(blank=True, default='', max_length=255)),
                ('school_fr', models.CharField(blank=True, default='', max_length=255)),
                ('school_en', models.CharField(blank=True, default='', max_length=255)),
                ('location_fr', models.CharField(blank=True, default='', max_length=255)),
                ('location_en', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['order', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('company_fr', models.CharField(blank=True, default='', max_length=255)),
                ('company_en', models.CharField(blank=True, default='', max_length=255)),
                ('location_fr', models.CharField(blank=True, default='', max_length=255)),
                ('location_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_fr', models.TextField(blank=True, default='', help_text='Une ligne = une puce')),
                ('description_en', models.TextField(blank=True, default='', help_text='One line = one bullet')),
                ('highlights_fr', models.TextField(blank=True, default='', help_text='Une ligne = un KPI / impact / résultat')),
                ('highlights_en', models.TextField(blank=True, default='', help_text='One line = one KPI / impact / result')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['order', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_fr', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('level_fr', models.CharField(blank=True, default='', max_length=100)),
                ('level_en', models.CharField(blank=True, default='', max_length=100)),
                ('progress', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='LEGRE Zaddy Wilfried Ghislain', max_length=150)),
                ('headline_fr', models.CharField(blank=True, default='', max_length=255)),
                ('headline_en', models.CharField(blank=True, default='', max_length=255)),
                ('bio_fr', models.TextField(blank=True, default='')),
                ('bio_en', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address_fr', models.CharField(blank=True, default='', max_length=255)),
                ('address_en', models.CharField(blank=True, default='', max_length=255)),
                ('footer_fr', models.CharField(blank=True, default='', max_length=255)),
                ('footer_en', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('keywords_fr', models.TextField(blank=True, default='', help_text='Mots-clés ATS séparés par des virgules ou des retours à la ligne')),
                ('keywords_en', models.TextField(blank=True, default='', help_text='ATS keywords separated by commas or line breaks')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_fr', models.CharField(blank=True, default='', max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('text_fr', models.CharField(blank=True, default='', max_length=255)),
                ('text_en', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Texte interface',
                'verbose_name_plural': 'Textes interface',
                'ordering': ['key'],
            },
        ),
    ]
